# Generated by Django 3.1.2 on 2020-11-04 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'cargo',
                'verbose_name_plural': 'cargos',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=20)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('cep', models.CharField(blank=True, max_length=20, null=True)),
                ('bairro', models.CharField(blank=True, max_length=150, null=True)),
                ('cidade', models.CharField(blank=True, max_length=150, null=True)),
                ('uf', models.CharField(blank=True, max_length=5, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=200)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.cargo')),
            ],
            options={
                'verbose_name': 'profissional',
                'verbose_name_plural': 'profissionais',
            },
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lei_complementar', models.CharField(max_length=200)),
                ('data_lei', models.DateField()),
                ('valor_comtrapartida', models.FloatField()),
                ('objeto', models.CharField(blank=True, max_length=150, null=True)),
                ('numero_proposta', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'proposta',
                'verbose_name_plural': 'propostas',
            },
        ),
        migrations.CreateModel(
            name='Prefeito',
            fields=[
                ('profissional_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.profissional')),
            ],
            options={
                'verbose_name': 'prefeito',
                'verbose_name_plural': 'prefeitos',
            },
            bases=('base.profissional',),
        ),
        migrations.CreateModel(
            name='SecretarioDeObras',
            fields=[
                ('profissional_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.profissional')),
            ],
            options={
                'verbose_name': 'secretário de obras',
                'verbose_name_plural': 'secretários de obras',
            },
            bases=('base.profissional',),
        ),
        migrations.CreateModel(
            name='SecretarioFinanceiro',
            fields=[
                ('profissional_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.profissional')),
            ],
            options={
                'verbose_name': 'secretário financeiro',
                'verbose_name_plural': 'secretários financeiro',
            },
            bases=('base.profissional',),
        ),
        migrations.CreateModel(
            name='Prefeitura',
            fields=[
                ('cliente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.cliente')),
                ('timbre', models.CharField(max_length=200, verbose_name='Papel timbrado')),
                ('prefeito', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.prefeito')),
                ('secretario_de_obras', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.secretariodeobras')),
                ('secretario_financeiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.secretariofinanceiro')),
            ],
            bases=('base.cliente',),
        ),
    ]
