# Generated by Django 3.1.2 on 2020-11-04 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposta',
            old_name='valor_comtrapartida',
            new_name='valor_contrapartida',
        ),
    ]
