# Generated by Django 3.1.3 on 2020-11-04 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20201103_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefeitura',
            name='timbre',
            field=models.ImageField(max_length=150, upload_to='uploads/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='data_lei',
            field=models.DateField(verbose_name='Data da lei'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='numero_proposta',
            field=models.CharField(max_length=150, verbose_name='Número da proposta'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='valor_contrapartida',
            field=models.FloatField(verbose_name='Valor da contrapartida'),
        ),
    ]
