# Generated by Django 3.1.3 on 2020-11-21 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20201103_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='prefeitura',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='base.prefeitura'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(max_length=20, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='uf',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='cpf',
            field=models.CharField(max_length=20, verbose_name='CPF'),
        ),
    ]
