# Generated by Django 3.1.3 on 2020-12-01 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20201121_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='situacao',
            field=models.CharField(choices=[('EA', 'Em análise'), ('EP', 'Empenhado'), ('AP', 'Aprovado'), ('RP', 'Reprovado')], default='EA', max_length=2),
        ),
    ]
