# Generated by Django 3.1.3 on 2020-12-01 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_proposta_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='situacao',
            field=models.CharField(choices=[('EN', 'Em análise'), ('EP', 'Empenhado'), ('AP', 'Aprovado'), ('RP', 'Reprovado')], default='EN', max_length=2),
        ),
    ]
