# Generated by Django 3.1.3 on 2020-12-01 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20201130_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='situacao',
            field=models.CharField(blank=True, choices=[('EN', 'Em análise'), ('EP', 'Empenhado'), ('AP', 'Aprovado'), ('RP', 'Reprovado')], default='EN', max_length=2, null=True),
        ),
    ]
