# Generated by Django 3.1.3 on 2020-12-01 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20201130_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.proposta')),
            ],
            options={
                'verbose_name': 'convênio',
                'verbose_name_plural': 'convênios',
            },
        ),
    ]
