# Generated by Django 3.1.3 on 2020-12-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_convenio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='situacao',
            field=models.CharField(blank=True, choices=[('em-analise', 'Em análise'), ('empenhado', 'Empenhado'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='em-analise', max_length=15, null=True),
        ),
    ]
