# Generated by Django 3.1.3 on 2020-12-02 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20201201_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposta',
            old_name='numero_proposta',
            new_name='numero',
        ),
    ]
