# Generated by Django 3.1.3 on 2020-12-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20201201_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='situacao',
            field=models.CharField(blank=True, choices=[('em-analise', 'Em análise'), ('empenhada', 'Empenhada'), ('aprovada', 'Aprovada'), ('reprovada', 'Reprovada')], default='em-analise', max_length=15, null=True),
        ),
    ]
