# Generated by Django 3.1.3 on 2020-12-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20201201_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='extrato',
            field=models.FileField(blank=True, max_length=150, null=True, upload_to='uploads/files/%Y/%m/%d'),
        ),
    ]
