# Generated by Django 3.1.3 on 2020-12-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20201202_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tipo_resposta',
            field=models.CharField(choices=[('checkbox', 'Check List'), ('radio', 'Opção'), ('text', 'Objetivo')], default=None, max_length=15),
        ),
    ]
