# Generated by Django 3.1.3 on 2020-12-02 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20201202_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='tipo_resposta',
        ),
    ]
