# Generated by Django 3.1.3 on 2020-12-02 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_item_tipo_resposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='subitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.item'),
        ),
        migrations.DeleteModel(
            name='Subitem',
        ),
    ]
