# Generated by Django 3.1.3 on 2020-12-02 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20201202_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.projeto'),
        ),
    ]
