# Generated by Django 3.1.3 on 2020-12-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20201202_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='descricao',
            field=models.TextField(),
        ),
    ]
