# Generated by Django 3.1.3 on 2020-12-02 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20201202_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='numero',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='respostaitem',
            name='resposta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.resposta'),
        ),
    ]
