# Generated by Django 3.1.3 on 2020-12-02 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20201202_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respostaitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='respostaitem',
            name='resposta',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Resposta',
        ),
        migrations.DeleteModel(
            name='RespostaItem',
        ),
    ]
