# Generated by Django 3.1.3 on 2020-12-05 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_projetopavimentacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projetopavimentacao',
            old_name='enquadramento_atte_atividade',
            new_name='atividade',
        ),
        migrations.RenameField(
            model_name='projetopavimentacao',
            old_name='enquadramento_atte_fonte',
            new_name='comentario_analise_tecnica',
        ),
        migrations.RenameField(
            model_name='projetopavimentacao',
            old_name='enquadramento_atte_linha',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='projetopavimentacao',
            old_name='enquadramento_atte_produto',
            new_name='fonte',
        ),
        migrations.RenameField(
            model_name='projetopavimentacao',
            old_name='mat',
            new_name='justificativa_comentarios',
        ),
        migrations.AddField(
            model_name='projetopavimentacao',
            name='linha',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='projetopavimentacao',
            name='matricula',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='projetopavimentacao',
            name='produto',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
