# Generated by Django 3.1.3 on 2020-12-05 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_auto_20201204_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetopavimentacao',
            name='art',
        ),
    ]
