# Generated by Django 3.1.3 on 2020-12-15 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_auto_20201214_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='orgao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.orgao'),
        ),
    ]
