# Generated by Django 3.1.3 on 2020-12-16 23:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_projeto_orgao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposta',
            name='data_lei',
        ),
        migrations.AddField(
            model_name='proposta',
            name='data',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data'),
            preserve_default=False,
        ),
    ]
