# Generated by Django 3.1.3 on 2020-12-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_estrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='tipo',
            field=models.CharField(blank=True, choices=[('estradas', 'Estradas'), ('pavimentacao', 'Pavimentacao')], default=None, max_length=150, null=True),
        ),
    ]
