# Generated by Django 3.1.3 on 2020-12-18 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_projeto_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('projeto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.projeto')),
                ('sr', models.CharField(blank=True, max_length=250, null=True)),
                ('numero_contrato', models.CharField(blank=True, max_length=250, null=True)),
                ('data_assinatura', models.CharField(blank=True, max_length=250, null=True)),
                ('programa', models.CharField(blank=True, max_length=250, null=True)),
                ('modalidade', models.CharField(blank=True, max_length=250, null=True)),
                ('proponente', models.CharField(blank=True, max_length=250, null=True)),
                ('tipo_proponente', models.CharField(blank=True, max_length=250, null=True)),
                ('empreendimento', models.CharField(blank=True, max_length=250, null=True)),
                ('localizacao', models.CharField(blank=True, max_length=250, null=True)),
                ('objetivo_pleito', models.CharField(blank=True, max_length=250, null=True)),
                ('copia_plano_trabalho', models.CharField(blank=True, max_length=250, null=True)),
                ('qci', models.CharField(blank=True, max_length=250, null=True)),
                ('especificacoes_detalhadas', models.CharField(blank=True, max_length=250, null=True)),
                ('orcamentos_detalhados', models.CharField(blank=True, max_length=250, null=True)),
                ('cotacao_mercado', models.CharField(blank=True, max_length=250, null=True)),
                ('cronograma_fisico_financeiro_empreendimento', models.CharField(blank=True, max_length=250, null=True)),
                ('plano_uso_equipamentos_adquiridos', models.CharField(blank=True, max_length=250, null=True)),
                ('documento_titularidade_area', models.CharField(blank=True, max_length=250, null=True)),
                ('art_projeto', models.CharField(blank=True, max_length=250, null=True)),
                ('art_orcamento', models.CharField(blank=True, max_length=250, null=True)),
                ('declaracao_munutencao_conservacao', models.CharField(blank=True, max_length=250, null=True)),
                ('declaracao_viabilidade_forneceimento_energia', models.CharField(blank=True, max_length=250, null=True)),
                ('declaracao_viabilidade_forneceimento_agua', models.CharField(blank=True, max_length=250, null=True)),
                ('declaracao_aquisicao_equipamentos', models.CharField(blank=True, max_length=250, null=True)),
                ('equipe_coordenacao_projeto', models.CharField(blank=True, max_length=250, null=True)),
                ('servico_apto_para_analise_tecnica', models.CharField(blank=True, max_length=250, null=True)),
                ('comentario_analise_tecnica', models.CharField(blank=True, max_length=250, null=True)),
                ('servico_terceirizado', models.CharField(blank=True, max_length=250, null=True)),
                ('justificativa_comentarios', models.CharField(blank=True, max_length=250, null=True)),
                ('atividade', models.CharField(blank=True, max_length=250, null=True)),
                ('produto', models.CharField(blank=True, max_length=250, null=True)),
                ('linha', models.CharField(blank=True, max_length=250, null=True)),
                ('fonte', models.CharField(blank=True, max_length=250, null=True)),
                ('responsavel_verificacao', models.CharField(blank=True, max_length=250, null=True)),
                ('data', models.CharField(blank=True, max_length=250, null=True)),
                ('local_data', models.CharField(blank=True, max_length=250, null=True)),
                ('responsavel_tecnico', models.CharField(blank=True, max_length=250, null=True)),
                ('matricula', models.CharField(blank=True, max_length=250, null=True)),
                ('cpf', models.CharField(blank=True, max_length=250, null=True)),
                ('crea', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'projeto de equipamento',
                'verbose_name_plural': 'projetos de equipamento',
            },
            bases=('base.projeto',),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='tipo',
            field=models.CharField(blank=True, choices=[('estradas', 'Estradas'), ('equipamento', 'Equipamento'), ('pavimentacao', 'Pavimentacao')], default=None, max_length=150, null=True),
        ),
    ]
