# Generated by Django 3.1.3 on 2020-12-19 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_auto_20201218_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edificacao',
            fields=[
                ('projeto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.projeto')),
                ('sr', models.CharField(blank=True, max_length=250, null=True)),
                ('numero_contrato', models.CharField(blank=True, max_length=250, null=True)),
                ('data_assinatura', models.CharField(blank=True, max_length=250, null=True)),
                ('programa', models.CharField(blank=True, max_length=250, null=True)),
                ('modalidade', models.CharField(blank=True, max_length=250, null=True)),
                ('proponente', models.CharField(blank=True, max_length=250, null=True)),
                ('tipo_proponente', models.CharField(blank=True, max_length=250, null=True)),
                ('empreendimento', models.CharField(blank=True, max_length=250, null=True)),
                ('localizacao', models.CharField(blank=True, max_length=250, null=True)),
                ('objetivo_pleito', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'projeto de edificacao',
                'verbose_name_plural': 'projetos de edificacao',
            },
            bases=('base.projeto',),
        ),
    ]
