# Generated by Django 3.1.3 on 2020-12-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_auto_20201219_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificacao',
            name='contrato_projeto_engenharia',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='edificacao',
            name='declaracao_contrapartida',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='edificacao',
            name='declaracao_execucao_obra',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='edificacao',
            name='equipe_coordenacao_projeto',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='edificacao',
            name='relatorio_fotografico',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
