# Generated by Django 3.1.3 on 2020-12-21 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_auto_20201220_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroEsportivo',
            fields=[
                ('edificacao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.edificacao')),
            ],
            options={
                'verbose_name': 'projeto de centro esportivo',
                'verbose_name_plural': 'projetos de centros esportivo',
            },
            bases=('base.edificacao',),
        ),
        migrations.CreateModel(
            name='Praca',
            fields=[
                ('edificacao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.edificacao')),
            ],
            options={
                'verbose_name': 'praça',
                'verbose_name_plural': 'praças',
            },
            bases=('base.edificacao',),
        ),
    ]
