# Generated by Django 3.1.3 on 2021-01-11 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_convenio_arquivo_extrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenio',
            name='proposta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.proposta'),
        ),
    ]
