# Generated by Django 3.1.3 on 2021-01-11 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0041_auto_20210110_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenio',
            name='numero_convenio',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Número convênio (SICONV)'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='convenio',
            name='orgao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.orgao'),
        ),
        migrations.AlterField(
            model_name='convenio',
            name='proposta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.proposta'),
        ),
        migrations.AlterField(
            model_name='prefeitura',
            name='prefeito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.prefeito'),
        ),
        migrations.AlterField(
            model_name='prefeitura',
            name='secretario_financeiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.secretariofinanceiro'),
        ),
        migrations.AlterField(
            model_name='prefeitura',
            name='secretario_obras',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.secretariodeobras'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.cargo'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.convenio'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='orgao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.orgao'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='prefeitura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.prefeitura'),
        ),
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=250)),
                ('data', models.DateField(auto_now=True, verbose_name='Data')),
                ('arquivo', models.FileField(blank=True, max_length=150, null=True, upload_to='uploads/%Y/%m/%d')),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.convenio')),
            ],
        ),
    ]
