# Generated by Django 3.1.3 on 2021-07-20 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_auto_20210719_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='tipo',
        ),
    ]
