# Generated by Django 3.1.3 on 2021-07-20 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_auto_20210719_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='projeto',
        ),
        migrations.AddField(
            model_name='item',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.projeto'),
        ),
        migrations.RemoveField(
            model_name='opcao',
            name='item',
        ),
        migrations.AddField(
            model_name='opcao',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.item'),
        ),
    ]
