# Generated by Django 3.1.3 on 2021-07-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_auto_20210719_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcao',
            name='alternativa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='opcao',
            name='descricao',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='opcao',
            name='texto',
            field=models.BooleanField(default=False),
        ),
    ]
