# Generated by Django 3.1.3 on 2021-07-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_item_observacoes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='item',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
