# Generated by Django 3.1.3 on 2021-07-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_auto_20210724_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('sort_order',)},
        ),
        migrations.AddField(
            model_name='item',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
        ),
    ]
