# Generated by Django 3.1.3 on 2021-07-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_auto_20210724_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
    ]
