# Generated by Django 3.1.3 on 2021-07-24 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_auto_20210724_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('order',)},
        ),
        migrations.RemoveField(
            model_name='item',
            name='sort_order',
        ),
    ]
