# Generated by Django 3.1.3 on 2021-07-25 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_alternativa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcao',
            name='item',
        ),
        migrations.RemoveField(
            model_name='opcao',
            name='usuario',
        ),
        migrations.AddField(
            model_name='item',
            name='opcao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.opcao'),
        ),
        migrations.CreateModel(
            name='ItemAlternativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternativa', models.ManyToManyField(to='base.Alternativa')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.item')),
            ],
        ),
    ]
