# Generated by Django 3.1.3 on 2021-07-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_auto_20210725_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('sort_order',), 'verbose_name_plural': 'itens'},
        ),
        migrations.AddField(
            model_name='opcao',
            name='responsavel',
            field=models.BooleanField(default=False),
        ),
    ]
