# Generated by Django 3.1.3 on 2021-07-28 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_auto_20210727_2316'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricoAtiviade',
            new_name='HistoricoAtividade',
        ),
    ]
