# Generated by Django 3.1.3 on 2021-07-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_auto_20210727_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolo',
            name='responsavel',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
