# Generated by Django 3.1.3 on 2021-07-28 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_protocolo_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='responsavel',
            field=models.CharField(blank=True, choices=[('agiliza', 'AGILIZA'), ('funasa', 'FUNASA'), ('prefeitura', 'PREFEITURA')], default=None, max_length=250, null=True),
        ),
    ]
