# Generated by Django 3.1.3 on 2021-07-28 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_auto_20210727_2333'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricoAtividade',
            new_name='Atividade',
        ),
    ]
