# Generated by Django 3.2.5 on 2021-07-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_auto_20210727_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='extrato',
            field=models.FileField(blank=True, max_length=150, null=True, upload_to='uploads/extrato/%Y/%m/%d'),
        ),
    ]
