# Generated by Django 3.2.5 on 2021-08-01 22:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_alter_proposta_extrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='data_prevista',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data Prevista'),
            preserve_default=False,
        ),
    ]
