# Generated by Django 3.2.5 on 2021-08-01 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_proposta_data_prevista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('profissional_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.profissional')),
            ],
            options={
                'verbose_name': 'responsável',
                'verbose_name_plural': 'responsáveis',
            },
            bases=('base.profissional',),
        ),
    ]
