# Generated by Django 3.2.5 on 2021-08-02 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0066_responsavel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoControle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('comentario', models.CharField(max_length=250)),
                ('data_prevista', models.DateField(verbose_name='Data Prevista')),
                ('alternativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.alternativa')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.item')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.responsavel')),
            ],
        ),
    ]
