# Generated by Django 3.2.5 on 2021-08-02 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_projetocontrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetocontrole',
            name='comentario',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='projetocontrole',
            name='data_prevista',
            field=models.DateField(blank=True, null=True, verbose_name='Data Prevista'),
        ),
        migrations.AlterField(
            model_name='projetocontrole',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.responsavel'),
        ),
    ]
