# Generated by Django 3.2.5 on 2021-08-02 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0068_auto_20210801_2137'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pavimentacao',
        ),
    ]
