# Generated by Django 3.2.5 on 2021-08-02 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0069_delete_pavimentacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipamento',
        ),
    ]
