# Generated by Django 3.2.5 on 2021-08-02 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0072_delete_centroesportivo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Praca',
        ),
    ]
