# Generated by Django 3.2.5 on 2021-08-02 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0073_delete_praca'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Edificacao',
        ),
    ]
