# Generated by Django 3.2.5 on 2021-08-08 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0075_auto_20210808_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetocontrole',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.projeto'),
        ),
    ]
