# Generated by Django 3.2.6 on 2021-08-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0077_auto_20210819_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='valor_contrapartida',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Valor da contrapartida'),
        ),
    ]
