# Generated by Django 3.2.6 on 2021-09-11 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0080_auto_20210911_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemalternativa',
            name='item',
        ),
        migrations.RemoveField(
            model_name='projetocontroleitem',
            name='item',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
