# Generated by Django 3.2.6 on 2021-09-11 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0081_auto_20210911_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=250)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateField(auto_now=True, verbose_name='Data de Criação')),
                ('sort_order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('opcao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.opcao')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.projeto')),
                ('subitem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.item')),
            ],
            options={
                'verbose_name_plural': 'itens',
                'ordering': ('sort_order',),
            },
        ),
        migrations.AddField(
            model_name='itemalternativa',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.item'),
        ),
        migrations.AddField(
            model_name='projetocontroleitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.item'),
        ),
    ]
