# Generated by Django 3.2.6 on 2021-09-11 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0084_auto_20210911_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='data_criacao',
            field=models.DateField(auto_now=True, verbose_name='Data de Criação'),
        ),
        migrations.AddField(
            model_name='item',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='opcao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.opcao'),
        ),
        migrations.AddField(
            model_name='item',
            name='order',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.projeto'),
        ),
        migrations.AddField(
            model_name='item',
            name='subitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.item'),
        ),
    ]
