# Generated by Django 3.2.6 on 2021-09-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0085_auto_20210911_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sort_order',
            field=models.PositiveIntegerField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
