# Generated by Django 3.2.8 on 2021-11-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0087_alter_item_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenio',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Valor'),
        ),
        migrations.AddField(
            model_name='convenio',
            name='valor_repasse',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Valor do repasse'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='tipo',
            field=models.CharField(blank=True, choices=[('estrada', 'Estrada'), ('equipamento', 'Equipamento'), ('praca', 'Praça'), ('pavimentacao', 'Pavimentação'), ('centro_esportivo', 'Centro Esportivo'), ('edificacao', 'Edificação')], default=None, max_length=150, null=True),
        ),
    ]
