# Generated by Django 3.2.8 on 2021-11-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0088_auto_20211107_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenio',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, null=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='convenio',
            name='valor_repasse',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, null=True, verbose_name='Valor do repasse'),
        ),
    ]
