# Generated by Django 3.2.8 on 2021-11-07 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0089_auto_20211107_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convenio',
            old_name='numero_convenio',
            new_name='numero',
        ),
    ]
