# Generated by Django 3.2.9 on 2021-11-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0091_auto_20211112_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='valor_contrapartida',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Valor da contrapartida'),
        ),
    ]
