# Generated by Django 3.2.9 on 2021-11-12 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0092_alter_proposta_valor_contrapartida'),
    ]

    operations = [
        migrations.CreateModel(
            name='TecnicoOrgao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'técnico orgão',
                'verbose_name_plural': 'técnicos orgãos',
            },
        ),
        migrations.AddField(
            model_name='convenio',
            name='tecnico_orgao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.tecnicoorgao'),
        ),
    ]
