# Generated by Django 3.2.9 on 2021-11-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0093_auto_20211112_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='valor_liberado',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, null=True, verbose_name='Valor liberado'),
        ),
    ]
