# Generated by Django 3.2.9 on 2021-11-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0094_proposta_valor_liberado'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenio',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proposta',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
