# Generated by Django 3.2.9 on 2021-11-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0095_auto_20211115_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='descricao',
            field=models.TextField(),
        ),
    ]
