# Generated by Django 3.2.9 on 2021-12-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0096_alter_item_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenio',
            name='data_suspensiva',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Cláusula Suspensiva'),
        ),
    ]
