# Generated by Django 3.2.9 on 2021-12-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0097_convenio_data_suspensiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenio',
            name='data_vigencia',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Vigência'),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='situacao',
            field=models.CharField(blank=True, choices=[('enviado_analise', 'Enviado p/ análise'), ('solicitada_complementacao', 'Solicitada complementação'), ('aprovado', 'Aprovado'), ('resolvido', 'Resolvido')], default=None, max_length=150, null=True),
        ),
    ]
