# Generated by Django 3.2.12 on 2022-02-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0099_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='tipo',
            field=models.CharField(blank=True, choices=[('estrada', 'Estrada'), ('equipamento', 'Equipamento'), ('praca', 'Praça'), ('pavimentacao', 'Pavimentação'), ('centro_esportivo', 'Centro Esportivo'), ('edificacao', 'Edificação'), ('outros', 'Outros')], default=None, max_length=150, null=True),
        ),
    ]
