# Generated by Django 3.2.12 on 2022-03-18 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0100_alter_projeto_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projetocontroleitem',
            options={'verbose_name': 'item', 'verbose_name_plural': 'itens'},
        ),
    ]
