# Generated by Django 3.2.12 on 2022-04-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0104_convenio_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenio',
            name='situacao',
            field=models.CharField(blank=True, choices=[('aguardando-aprovacao', 'Aguardando aprovação do projeto'), ('projeto-aprovado', 'Projeto aprovado'), ('aguardando-licitacao', 'Aguardando licitação'), ('aguardando-aceite-licitacao', 'Aguardando aceite da licitação'), ('licitacao-aprovada', 'Licitação aprovada, aguardando recurso'), ('recurs-em-conta', 'Recurso em conta'), ('em-execucao', 'Em execução'), ('convenio-concluido', 'Convenio concluído'), ('prestacao-de-contas-concluida', 'Prestação de contas concluída')], default='aguardando-aprovacao', max_length=50, null=True),
        ),
    ]
