# Generated by Django 3.2.12 on 2022-04-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0106_alter_convenio_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenio',
            name='data_aprovacao_projeto',
            field=models.DateField(blank=True, null=True, verbose_name='Data Aprovação de Projeto'),
        ),
    ]
