# Generated by Django 3.2.12 on 2022-04-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0107_convenio_data_aprovacao_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenio',
            name='data_analise_projeto',
            field=models.DateField(blank=True, null=True, verbose_name='Data Licitação de Projeto'),
        ),
        migrations.AddField(
            model_name='convenio',
            name='data_licitacao_projeto',
            field=models.DateField(blank=True, null=True, verbose_name='Data Licitação de Projeto'),
        ),
    ]
