# Generated by Django 3.2.12 on 2022-04-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0108_auto_20220427_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convenio',
            name='data_analise_projeto',
        ),
        migrations.AddField(
            model_name='convenio',
            name='data_analise_licitacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data Análise de Licitação'),
        ),
    ]
