# Generated by Django 3.2.12 on 2022-04-28 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0109_auto_20220427_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenio',
            name='data_aceite_licitacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data Aceite de Licitação'),
        ),
    ]
