# Generated by Django 3.2.12 on 2022-04-28 03:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0110_convenio_data_aceite_licitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenio',
            name='data_liberacao_recurso',
            field=models.DateField(blank=True, null=True, verbose_name='Data Liberação do Recurso'),
        ),
        migrations.AddField(
            model_name='convenio',
            name='valor_recurso',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=19, null=True, verbose_name='Valor do recurso'),
        ),
    ]
