# Generated by Django 3.2.12 on 2022-04-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0111_auto_20220428_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenio',
            name='data_conclusao',
            field=models.DateField(blank=True, null=True, verbose_name='Data Conclusão'),
        ),
        migrations.AlterField(
            model_name='convenio',
            name='situacao',
            field=models.CharField(blank=True, choices=[('aguardando-aprovacao', 'Aguardando aprovação do projeto'), ('projeto-aprovado', 'Projeto aprovado'), ('aguardando-licitacao', 'Aguardando licitação'), ('aguardando-aceite-licitacao', 'Aguardando aceite da licitação'), ('licitacao-aprovada', 'Licitação aprovada, aguardando recurso'), ('recurso-em-conta', 'Recurso em conta, em execução'), ('convenio-concluido', 'Convenio concluído'), ('prestacao-de-contas-concluida', 'Prestação de contas concluída')], default='aguardando-aprovacao', max_length=50, null=True),
        ),
    ]
