# Generated by Django 3.2.12 on 2022-04-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0112_auto_20220428_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenio',
            name='data_prestacao_contas',
            field=models.DateField(blank=True, null=True, verbose_name='Data Conclusão'),
        ),
    ]
