# Generated by Django 3.2.13 on 2022-05-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0113_convenio_data_prestacao_contas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenio',
            name='situacao',
            field=models.CharField(blank=True, choices=[('aguardando-aprovacao', 'Aguardando aprovação do projeto'), ('projeto-aprovado', 'Projeto aprovado, aguardando licitação'), ('aguardando-aceite-licitacao', 'Aguardando aceite da licitação'), ('licitacao-aprovada', 'Licitação aprovada, aguardando recurso'), ('recurso-em-conta', 'Recurso em conta, em execução'), ('convenio-concluido', 'Convenio concluído'), ('prestacao-de-contas-concluida', 'Prestação de contas concluída')], default='aguardando-aprovacao', max_length=50, null=True),
        ),
    ]
