# Generated by Django 3.2.13 on 2022-09-08 02:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0114_alter_convenio_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenio',
            name='cnpj_empresa_contratada',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ empresa contratada'),
        ),
        migrations.AddField(
            model_name='convenio',
            name='data_contrato',
            field=models.DateField(blank=True, max_length=150, null=True, verbose_name='Data contrato'),
        ),
        migrations.AddField(
            model_name='convenio',
            name='nome_empresa_contratada',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Empresa contratada'),
        ),
        migrations.AddField(
            model_name='convenio',
            name='numero_contrato',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Número contrato'),
        ),
        migrations.AddField(
            model_name='convenio',
            name='valor_contrato',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=19, null=True, verbose_name='Valor contrato'),
        ),
        migrations.AddField(
            model_name='convenio',
            name='vigencia_contrato',
            field=models.DateField(blank=True, max_length=150, null=True, verbose_name='Vigência contrato'),
        ),
    ]
