# Generated by Django 3.2.13 on 2022-10-07 21:29

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0115_auto_20220907_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecucaoConvenente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcela', models.IntegerField(verbose_name='Parcela')),
                ('data_pagamento', models.DateField(verbose_name='Data pagamento')),
                ('valor_pagamento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19, verbose_name='Valor pagamento')),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.convenio')),
            ],
        ),
    ]
