# Generated by Django 3.2.15 on 2024-04-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0118_auto_20240412_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='responsavel',
            field=models.CharField(blank=True, choices=[('agiliza', 'AGILIZA'), ('funasa', 'FUNASA'), ('prefeitura', 'PREFEITURA'), ('assessoria', 'ASSESSORIA'), ('gabinete_parlamentar', 'GABINETE PARLAMENTAR'), ('orgao_convenente', 'ORGAO CONVENENTE'), ('concedente', 'CONCEDENTE'), ('outros', 'OUTROS')], default=None, max_length=250, null=True),
        ),
    ]
